/* DIFERENÇA ENTRE CHAR E VARCHAR */

CHAR(10)
JOAO      - O RESTANTE DOS ESPAÇOS SERA PREENCHIDO COM ESPAÇO, CONSUMINDO MAIS BYTES

                                             EM QUANTO

VARCHAR(10)
JOAO    -  FAZ A VARIAÇÃO CONFORME O DADO, UTILIZANDO APENAS O VALOR "JOAO" E CONSUMINDO MENOS BYTES

