/* O COMANDO SELECT (SELEÇÃO PROJEÇÃO E JUNÇÃO */

SELECT NOW();

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */