/* FILTRANDO VALORES NULOS */


/* PEGA TODOS OS EMAILS QUE ESTIVEREM NULL */
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

/* PEGA TODOS OS EMAILS QUE NÃO SÃO NULL */
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;


