/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */

UPDATE CLIENTE
SET EMAIL = 'JOAOA@IG.COM.BR'
WHERE NOME = 'JOAO';

UPDATE CLIENTE
SET EMAIL = 'JORGE@IG.COM.BR'
WHERE NOME = 'JORGE';

UPDATE CLIENTE 
SET EMAIL = 'LILIAN@IG.COM.BR'
WHERE NOME = 'LILIAN'
