


/* VENDEDOR QUE VENDEU MENOS EM MARCO E O SEU NOME */
SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);


/* NOME E O VALOR QUE VENDEU MAIS EM MARCO */
SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(FEVEREIRO) FROM VENDEDORES);


/* QUEM VENDEU MAIS QUE O VALOR MEDIO DE FEV */
SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

